CREATE TABLE STUDENT 
(
  NO INTEGER NOT NULL 
, NAME NCHAR(10) 
, COLUMN2 NCHAR(20) 
, COLUMN3 NCHAR(80) 
, COLUMN4 NCHAR(20) 
, CONSTRAINT STUDENT_PK PRIMARY KEY 
  (
    NO 
  )
  ENABLE 
);

COMMENT ON COLUMN STUDENT.NO IS '학번';
COMMENT ON COLUMN STUDENT.NAME IS '성명';
COMMENT ON COLUMN STUDENT.DET IS '전공';
COMMENT ON COLUMN STUDENT.ADDR IS '주소';
COMMENT ON COLUMN STUDENT.TEL IS '전화번호';

INSERT INTO STUDENT VALUES(1, '홍길동', '국문학과', '서울', '010-1111-1111');
INSERT INTO STUDENT VALUES(2, '고길동', '수학과', '인천', '010-2222-2222');

